import type { SupportedRouteItem } from "./types";

export const defaultPageTitle = 'PoC of GTM + GA4' as const;
export const defaultPageDescription = 'A GTM + GA4 playground, generated by Cloudflare C3' as const;

export const GTM_ID = String(process.env.NEXT_PUBLIC_GTM_ID);

export const supportedRoutes = [
  {
    key: 'home',
    page: 'Home',
    route: '/',
  },
  {
    key: 'about',
    page: 'About',
    route: '/about'
  },
  {
    key: 'other',
    page: 'Other',
    route: '/other'
  },
  {
    key: 'error',
    page: 'Error',
    route: '/error'
  },
] as const satisfies SupportedRouteItem[];

